name: push

on:
  workflow_call:

jobs:
  push:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Setup flake environment
        run: nix develop -c sleep 0
        shell: bash

      - name: Push Docker image
        run: |-
          set -e

          echo "${{ secrets.GITHUB_TOKEN }}" | skopeo login ghcr.io -u "${{ github.actor }}" --password-stdin
          $(nix build --no-link --print-out-paths '.#dockerImage') | gzip --fast | skopeo copy docker-archive:/dev/stdin docker://ghcr.io/${{ github.repository }}:latest
