name: Master

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  push:
    needs: [check]
    uses: ./.github/workflows/_push.yml
